version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "dependabot"

  - package-ecosystem: "npm"
    directory: "/ied-be"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "dependabot"
      - "ied-be"

  - package-ecosystem: "npm"
    directory: "/ied-fe"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "dependabot"
      - "ied-fe"

  - package-ecosystem: "npm"
    directory: "/ied-shared"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "dependabot"
      - "ied-shared"

  - package-ecosystem: "npm"
    directory: "/mongo-migrator"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "dependabot"
      - "mongo-migrator"
