version: 2
updates:
  # Enable version updates for pnpm
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    # Specify labels for Dependabot PRs
    labels:
      - "dependencies"
      - "dependabot"
    # Specify the directories for each package within the monorepo
    registries:
      - "*"
    ignore:
      # Ignore updates to node itself
      - dependency-name: "node"
      - dependency-name: "npm"

  # Maintain dependencies for ied-be
  - package-ecosystem: "npm"
    directory: "/ied-be"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "dependabot"
      - "ied-be"

  # Maintain dependencies for ied-fe
  - package-ecosystem: "npm"
    directory: "/ied-fe"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "dependabot"
      - "ied-fe"

  # Maintain dependencies for ied-shared
  - package-ecosystem: "npm"
    directory: "/ied-shared"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "dependabot"
      - "ied-shared"

  # Maintain dependencies for mongo-migrator
  - package-ecosystem: "npm"
    directory: "/mongo-migrator"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "dependabot"
      - "mongo-migrator" 